alias migrate='rake db:migrate db:test:clone'
alias aliases='vi ~/.zprofile; source ~/.zprofile'
alias rgm='rails g migration'
alias gpr='git pull -r'
alias db_reset='bundle exec rake db:drop db:create db:migrate && bundle exec rake db:seed db:test:clone'

alias vimrc='vi ~/.vimrc'
alias ctagit='ctags -R --language-force=ruby --exclude=.git --exclude=log --exclude=.md --exclude=coverage --exclude=tmp * `bundle show --paths`'
alias add_to_vim_bundle='cd ~/.vim/bundle && git clone '

export BUNDLER_EDITOR=vi
export DISABLE_COVERAGE=true
export EDITOR=vi
